services:
  code-tunnel:
    build: .
    container_name: code-tunnel
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - code_tunnel_home:/home/tunnel
      - ./gitconfig:/home/tunnel/.gitconfig:ro
      - ~/Projects:/home/tunnel/Projects:ro
      - ~/Projects/algorithm-practice:/home/tunnel/Projects/algorithm-practice:rw

volumes:
  code_tunnel_home:
